import React from 'react'
import NavBar from './NavBar'
import Head from 'next/head'
import Footer from './Footer'

const Layout = ({children}) => {
  return (
    <div>
      <Head>
        <title>Caffeina Politica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="favicon.ico" />
      </Head>
      <NavBar /> 
      {children}
      <Footer />
    </div>
  )
}

export default Layout