import Head from 'next/head'

import { Inter } from '@next/font/google'

import Hero from '../components/Hero'
import Eventi from '../components/Eventi'
import Grid from '../components/Grid'
import Articoli from '../components/Articoli'
import AboutUs from '../components/AboutUs'
import Footer from '../components/Footer'
import Contatti from '../components/Contatti'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Caffeina Politica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Eventi/>
      <Articoli/>
      <AboutUs/>
      <Contatti />
      <Footer />
    </>
  )
}
